version: '3.8'

services:
  # Backend API
  pension-api:
    build:
      context: ./ApiBackend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_PORT=8080
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React App
  pension-frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_BASE_URL=http://api.fmroz.me:8080
        - REACT_APP_ENV=production
        - REACT_APP_USE_MOCK_DATA=false
    ports:
      - "3000:80"
    depends_on:
      - pension-api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx reverse proxy (optional, for production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - pension-frontend
      - pension-api
    restart: unless-stopped
    profiles:
      - production

volumes:
  data:
    driver: local

networks:
  default:
    name: pension-network