POST http://localhost:8080/pensions/calculate
Content-Type: application/json
Accept: application/json

{
  "expectedPensionPLN": 12000.0,
  "age": 35,
  "sex": "F",
  "grossSalaryPLN": 22500.0,
  "startYear": 2012,
  "plannedEndYear": 2060,
  "includeSickLeave": true,
  "zusAccountFundsPLN": 35000.5,
  "postalCode": "02-776",
  "contractType": "UMOWA_O_PRACE",
  "additionalSickLeaveDaysPerYear": 10,
  "additionalSalaryChanges": [
    { "changeType": "BREAK", "startDate": "2024-02-10T00:00:00Z", "endDate": "2024-12-31T23:59:59Z" },
    { "changeType": "BREAK", "startDate": "2030-01-01T00:00:00Z", "endDate": "2031-12-31T23:59:59Z" }
  ]
}